language: node_js
node_js:
    - 12
install:
    - npm install -g serverless
    - npm install
script:
    - npm test
    - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
    - serverless deploy