language: node_js
node_js:
  - 12
services:
  - docker
install:
  - npm install -g serverless
  - npm install
script:
  - docker build -t kokjianyu/simple-web-app-backend-javascript .
  - docker-compose up -d
  - sleep 20
  - npm test
  - docker-compose down
after_success:
  - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
  - serverless deploy
