version: '3.7'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
  app-node:
    depends_on:
        - "dynamodb-local"
    links:
        - "dynamodb-local"
    image: kokjianyu/simple-web-app-backend-javascript:latest
    container_name: app-node
    ports:
     - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYID'
      AWS_SECRET_ACCESS_KEY: 'DUMMYID'
      AWS_REGION: 'ap-southeast-1'